AWSTemplateFormatVersion: '2010-09-09'
Description: ALB ASG Stack Andrea-Andres

Resources:

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: ALB-ASG-Andrea-Andres
      LaunchTemplateData:

        ImageId: ami-0cca150d127c2216f
        InstanceType: t2.micro

        SecurityGroupIds:
          - !ImportValue EC2SecurityGroupId

        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>ASG Andrea Andres</h1>" > /var/www/html/index.html

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TG-Andrea-Andres
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: vpc-05777cf4d0d1b1c0f
      HealthCheckPath: /
      HealthCheckProtocol: HTTP

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ALB-Andrea-Andres
      Scheme: internet-facing

      SecurityGroups:
        - !ImportValue ALBSecurityGroupId

      Subnets:
        - subnet-0628d873871536ee2
        - subnet-0c39c521b9d4f225f

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:

      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'

      VPCZoneIdentifier:
        - subnet-0628d873871536ee2
        - subnet-0c39c521b9d4f225f

      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber

      TargetGroupARNs:
        - !Ref TargetGroup

      Tags:
        - Key: Name
          Value: ASG-Andrea-Andres
          PropagateAtLaunch: true

  WarmPool:
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      MinSize: 1

Outputs:

  LoadBalancerDNS:
    Description: DNS del Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  LaunchTemplateId:
    Description: Launch Template ID
    Value: !Ref LaunchTemplate

  AutoScalingGroupName:
    Description: Auto Scaling Group Name
    Value: !Ref AutoScalingGroup

  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref TargetGroup