AWSTemplateFormatVersion: '2010-09-09'
Description: Security Stack Andrea-Andres

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group EC2
      GroupName: SecurityGroups-EC2-Andrea-Andres
      VpcId: vpc-05777cf4d0d1b1c0f
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group ALB
      GroupName: SecurityGroups-ALB-Andrea-Andres
      VpcId: vpc-05777cf4d0d1b1c0f
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:

  EC2SecurityGroupId:
    Value: !Ref EC2SecurityGroup
    Export:
      Name: EC2SecurityGroupId

  ALBSecurityGroupId:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: ALBSecurityGroupId