name: Deploy

on:
  workflow_dispatch:

jobs:

  Deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Deploy Security
      run: |
        aws cloudformation deploy \
        --stack-name Security-Andrea-Andres \
        --template-file templates/security.yml

    - name: Deploy EC2
      run: |
        aws cloudformation deploy \
        --stack-name EC2-Andrea-Andres \
        --template-file templates/ec2.yml

    - name: Deploy ALB-ASG
      run: |
        aws cloudformation deploy \
        --stack-name ALB-ASG-Andrea-Andres \
        --template-file templates/alb-asg.yml

    - name: Deploy Automation
      run: |
        aws cloudformation deploy \
        --stack-name Automation-Andrea-Andres \
        --template-file templates/automation.yml